title:              qnbz209
email:              qnbz209@gmail.com
description:        기록 저장소
author:             qnbz209
baseurl:            ""
url:                "https://qnbz209.github.io"

# Social Profiles
twitter_username:
github_username:    qnbz209
facebook_username:
instagram_username: qnbz209
linkedin_username:  qnbz209

# Add your google-analytics ID here to activate google analytics
google_analytics:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
